data:
  test_size: 0.2
  random_state: 42
  # Feature engineering
  lag_hours: [3, 6]
  rolling_window: 6
  columns_to_lag_and_window: ['wave_height_significant_m', 'wave_direction_deg']

model:
  random_state: 42

training:
  n_trials: 20
  active_model: random_forest  # 'random_forest' or 'hist_gradient_boosting'

models:
  random_forest:
    random_state: 42
    optuna_params:
      n_estimators:
        type: int
        low: 50
        high: 200
      max_depth:
        type: int
        low: 5
        high: 20
      min_samples_split:
        type: int
        low: 2
        high: 10
      min_samples_leaf:
        type: int
        low: 1
        high: 10
      max_features:
        type: categorical
        choices:
        - sqrt
        - log2
        - null
  hist_gradient_boosting:
    random_state: 42
    optuna_params:
      max_iter:
        type: int
        low: 100
        high: 1000
      max_depth:
        type: int
        low: 3
        high: 15
      learning_rate:
        type: float
        low: 0.01
        high: 0.3
        log: true
      min_samples_leaf:
        type: int
        low: 5
        high: 50
      l2_regularization:
        type: float
        low: 0
        high: 10
